=== ednet-dev/cms/packages/code_generation/dsl/schema/json/schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema for a JSON execution of EDNetCoreDSL",
  "definitions": {
    "attribute": {
      "description": "Attribute definition",
      "type": "object",
      "properties": {
        "sequence": {
          "description": "The order in which the attribute appears in the UI",
          "type": "integer"
        },
        "category": {
          "description": "The category of the attribute (e.g. identifier, required, attribute)",
          "type": "string"
        },
        "name": {
          "description": "The name of the attribute",
          "type": "string"
        },
        "type": {
          "description": "The data type of the attribute (e.g. String, bool)",
          "type": "string"
        },
        "init": {
          "description": "The initial value of the attribute",
          "type": "string"
        },
        "essential": {
          "description": "Whether this attribute is required",
          "type": "boolean"
        },
        "sensitive": {
          "description": "Whether this attribute contains sensitive information",
          "type": "boolean"
        }
      },
      "required": [
        "sequence",
        "category",
        "name",
        "type",
        "essential",
        "sensitive"
      ]
    },
    "box": {
      "description": "Concept definition",
      "type": "object",
      "properties": {
        "name": {
          "description": "The name of the Concept",
          "type": "string"
        },
        "entry": {
          "description": "Whether this is the entry Concept (Aggregate root) for the model",
          "type": "boolean"
        },
        "x": {
          "description": "The x-coordinate of the top-left corner of the canvas artifact",
          "type": "integer"
        },
        "y": {
          "description": "The y-coordinate of the top-left corner of the canvas artifact",
          "type": "integer"
        },
        "width": {
          "description": "The width of the canvas artifact",
          "type": "integer"
        },
        "height": {
          "description": "The height of the canvas artifact",
          "type": "integer"
        },
        "attributes": {
          "description": "An array of attributes defining the Concept",
          "type": "array",
          "attributes": {
            "$ref": "#/definitions/attribute"
          }
        }
      },
      "required": [
        "name",
        "entry",
        "x",
        "y",
        "width",
        "height",
        "attributes"
      ]
    },
    "relationship": {
      "type": "object",
      "properties": {
        "from": {
          "description": "The name of the first Concept in the relationship.",
          "type": "string"
        },
        "to": {
          "description": "The name of the second Concept in the relationship.",
          "type": "string"
        },
        "fromToName": {
          "description": "The name of the relationship.",
          "type": "string"
        },
        "fromToMin": {
          "description": "The minimum number of instances of the second Concept in the relationship.",
          "type": "string"
        },
        "fromToMax": {
          "description": "The maximum number of instances of the second Concept in the relationship.",
          "type": "string"
        },
        "toFromName": {
          "description": "The name of the inverse relationship.",
          "type": "string"
        },
        "toFromMin": {
          "description": "The minimum number of instances of the first Concept in the inverse relationship.",
          "type": "string"
        },
        "toFromMax": {
          "description": "The maximum number of instances of the first Concept in the inverse relationship.",
          "type": "string"
        },
        "category": {
          "description": "The \"category\" field in model.json files can take on different values depending on the type of relationship being defined between concepts. The most commonly used value is \"relationship\", which indicates a standard relationship between concepts. Another value is \"twin\", which indicates a special type of relationship where two concepts are related to each other in a symmetrical manner. \"Reflexive\" indicates a relationship where a concept has a relationship with itself, and \"inheritance\" indicates a relationship where a child concept inherits properties from a parent concept.",
          "type": "string"
        },
        "internal": {
          "description": "Indicates whether the relationship is internal to the Concept, i.e., whether it is used for implementation purposes only and have no public API beside what Parent Concept provides.",
          "type": "boolean"
        },
        "fromToId": {
          "description": "Whether the relationship involves an identifier from the second Concept.",
          "type": "boolean"
        },
        "toFromId": {
          "description": "Whether the inverse relationship involves an identifier from the first Concept.",
          "type": "boolean"
        }
      },
      "required": [
        "from",
        "to",
        "fromToName",
        "fromToMin",
        "fromToMax",
        "toFromName",
        "toFromMin",
        "toFromMax",
        "category",
        "internal",
        "fromToId",
        "toFromId"
      ]
    }
  },
  "type": "object",
  "properties": {
    "width": {
      "description": "The width of the canvas",
      "type": "integer"
    },
    "relations": {
      "description": "An array of relationships between Concepts",
      "type": "array",
      "attributes": {
        "$ref": "#/definitions/relationship"
      }
    },
    "height": {
      "description": "The height of the canvas",
      "type": "integer"
    },
    "concepts": {
      "description": "Array of EDNetCore Concepts",
      "type": "array",
      "attributes": {
        "$ref": "#/definitions/box"
      }
    }
  },
  "required": [
    "width",
    "relations",
    "height",
    "concepts"
  ]
}

=== ednet-dev/cms/apps/ednet_core/tasks/model.json
{
    "width":990,
    "height":580,
    "concepts":[
        {
            "name":"Employee",
            "entry":true,
            "x":474,
            "y":43,
            "width":80,
            "height":80,
            "attributes":[
                {
                    "sequence":10,
                    "name":"email",
                    "category":"identifier",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"lastName",
                    "category":"required",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":30,
                    "name":"firstName",
                    "category":"required",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Project",
            "entry":true,
            "x":63,
            "y":43,
            "width":80,
            "height":80,
            "attributes":[
                {
                    "sequence":10,
                    "name":"name",
                    "category":"identifier",
                    "type":"String",
                    "init":"",
                    "essential":true,
                    "sensitive":false
                },
                {
                    "sequence":20,
                    "name":"description",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                }
            ]
        },
        {
            "name":"Task",
            "entry":false,
            "x":270,
            "y":223,
            "width":80,
            "height":60,
            "attributes":[
                {
                    "sequence":10,
                    "name":"description",
                    "category":"attribute",
                    "type":"String",
                    "init":"",
                    "essential":false,
                    "sensitive":false
                }
            ]
        }
    ],
    "relations":[
        {
            "from":"Project",
            "to":"Task",
            "category":"relationship",
            "internal":true,
            "fromToName":"tasks",
            "fromToMin":"0",
            "fromToMax":"N",
            "fromToId":false,
            "toFromName":"project",
            "toFromMin":"1",
            "toFromMax":"1",
            "toFromId":true
        },
        {
            "from":"Employee",
            "to":"Task",
            "category":"relationship",
            "internal":true,
            "fromToName":"tasks",
            "fromToMin":"0",
            "fromToMax":"N",
            "fromToId":false,
            "toFromName":"employee",
            "toFromMin":"1",
            "toFromMax":"1",
            "toFromId":true
        }
    ]
}

=== ednet-dev/cms/packages/content/context/ednet/project_management/focus_management/model.json
{
    "width": 3000,
    "height": 3000,
    "concepts": [
        {
            "name": "Focus",
            "entry": true,
            "x": 1255,
            "y": 1143,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "Task",
            "entry": true,
            "x": 1682,
            "y": 1141,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "Project",
            "entry": true,
            "x": 1936,
            "y": 1140,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "User",
            "entry": true,
            "x": 1441,
            "y": 982,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "DueDate",
            "entry": true,
            "x": 1857,
            "y": 1427,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "Priority",
            "entry": true,
            "x": 2025,
            "y": 1424,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "DueDateChangeComment",
            "entry": true,
            "x": 1924,
            "y": 1701,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "Urgency",
            "entry": true,
            "x": 1938,
            "y": 1280,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "PriorityChangeComment",
            "entry": true,
            "x": 1741,
            "y": 1703,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "DescisionEngine",
            "entry": true,
            "x": 1439,
            "y": 1140,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "UrgencyEstimation",
            "entry": true,
            "x": 1437,
            "y": 1304,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "CommitmentType",
            "entry": true,
            "x": 2203,
            "y": 1135,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "GovernmentCommitment",
            "entry": true,
            "x": 2382,
            "y": 979,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "ProffesionalCommitment",
            "entry": true,
            "x": 2382,
            "y": 1130,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "PrivateCommitment",
            "entry": true,
            "x": 2381,
            "y": 1296,
            "width": 120,
            "height": 120,
            "attributes": []
        },
        {
            "name": "SelfCommitment",
            "entry": true,
            "x": 2381,
            "y": 1440,
            "width": 120,
            "height": 120,
            "attributes": []
        }
    ],
    "relations": []
}

=== ednet-dev/cms/packages/types/model.json
{
   "width":990,
   "height":580,
   "concepts":[
      {
         "name":"Type",
         "entry":true,
         "x":207,
         "y":236,
         "width":120,
         "height":200,
         "attributes":[
            {
               "sequence":10,
               "name":"sequence",
               "category":"identifier",
               "type":"int",
               "init":"increment",
               "essential":true,
               "sensitive":false
            },
            {
               "sequence":20,
               "name":"title",
               "category":"required",
               "type":"String",
               "init":"",
               "essential":true,
               "sensitive":false
            },
            {
               "sequence":30,
               "name":"email",
               "category":"attribute",
               "type":"Email",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":40,
               "name":"started",
               "category":"attribute",
               "type":"DateTime",
               "init":"now",
               "essential":true,
               "sensitive":false
            },
            {
               "sequence":50,
               "name":"price",
               "category":"attribute",
               "type":"double",
               "init":"0",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":60,
               "name":"qty",
               "category":"attribute",
               "type":"num",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":70,
               "name":"completed",
               "category":"attribute",
               "type":"bool",
               "init":"false",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":80,
               "name":"whatever",
               "category":"attribute",
               "type":"dynamic",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":90,
               "name":"web",
               "category":"attribute",
               "type":"Uri",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":100,
               "name":"other",
               "category":"attribute",
               "type":"Other",
               "init":"",
               "essential":false,
               "sensitive":false
            },
            {
               "sequence":110,
               "name":"note",
               "category":"attribute",
               "type":"String",
               "init":"",
               "essential":false,
               "sensitive":false
            }
         ]
      }
   ],
   "relations":[

   ]
}
